@startuml

class Observable {}
struct "std::hash<Observable>" as ObservableHash {
    +std::size_t operator() (const Observable& observable) const noexcept
}

package abstractions {
        package general {
            class ObservablePatch {
                --data members--
                -m_observable: Observable
                -m_patch: const Poly&
                -m_hashcode: std::size_t
                --constructors--
                +ObservablePatch(Observable observable, const Poly& patch)
                +ObservablePatch(const ObservablePatch& other)
                +ObservablePatch(ObservablePatch&& other)
                --member functions--
                +observable(): Observable
                +observableInterpretation(): PowersetConstSharedPtr
                +patch(): const Poly&
                +spaceDimension(): PPL::dimension_type
                +hashcode(): std::size_t
                --operators--
                +operator!= (const ObservablePatch& patchObservable1, const ObservablePatch& patchObservable2) : bool
                +operator== (const ObservablePatch& patchObservable1, const ObservablePatch& patchObservable2) : bool
            }

            ObservablePatch --> "1" Observable

            class ObservablePatchSequence {
                --data members--
                -m_sequence: std::vector<ObservablePatch>
                -m_hashcode: std::size_t
                -m_spaceDimension: PPL::dimension_type
                --constructors--
                +ObservablePatchSequence(std::vector<ObservablePatch> sequence, PPL::dimension_type spaceDimension)
                +ObservablePatchSequence(const ObservablePatchSequence& other)
                +ObservablePatchSequence(ObservablePatchSequence&& other)
                --member functions--
                +sequence(): const std::vector<ObservablePatch>&
                +cbegin(): std::vector<ObservablePatch>::const_iterator
                +cend(): std::vector<ObservablePatch>::const_iterator
                +isEmpty(): bool
                +totalPatches(): int
                +firstObservablePatch(): std::optional<const ObservablePatch* const>
                +spaceDimension(): PPL::dimension_type
                +hashcode(): std::size_t
                -computeHashCode(): void
                --operators--
                +operator!= (const ObservablePatchSequence& seq1, const ObservablePatchSequence& seq2) : bool
                +operator== (const ObservablePatchSequence& seq1, const ObservablePatchSequence& seq2) : bool
            }

            struct "std::hash<ObservablePatchSequence>" as ObservablePatchSequenceHash {
                +std::size_t operator() (const ObservablePatchSequence& observablePatchSequence) const noexcept
            }

            struct "std::hash<ObservablePatch>" as ObservablePatchHash {
                +std::size_t operator() (const ObservablePatch& observablePatch) const noexcept
            }

            ObservablePatchSequence <..> ObservablePatchHash
            ObservablePatch <..> ObservablePatchSequenceHash
            Observable <..> ObservableHash

            class ObservableTraversalNode {
                --data members--
                -m_travPoints: PowersetSharedPtr
                -m_observable: Observable
                -m_isSing: bool
                --constructors--
                +ObservableTraversalNode(ObservablePatchSequence sequence, const Poly& preFlow, bool isSing = false)
                --member functions--
                +travPoints(): PowersetConstSharedPtr
                +observable(): Observable
                +spaceDimension(): PPL::dimension_type
                +isSing(): bool
                +isEmpty(): bool
                +isUniverse(): bool
            }

            ObservablePatchSequence --> "1...*" ObservablePatch
            ObservableTraversalNode --> "1" Observable
            ObservableTraversalNode ..> ObservablePatchSequence

            class GeneralPolyhedralAbstraction {
                --data members--
                -m_graph: spot::twa_graph_ptr
                -m_sufficientHorizon: int
                -m_totalTrees: int
                -m_nodeByState: std::unordered_map<int, ObservableTraversalNode>
                --constructors--
                +GeneralPolyhedralAbstraction(PolyhedralSystemConstSharedPtr polyhedralSystem, int totalStatesFiniteAutomaton)
                --member function--
                +points(int state): PowersetConstSharedPtr
                +observable(int state): const Observable&
                +sufficientHorizon(): int
                +totalTrees(): int
            }

            class SingOpenStatePair {
                --data members--
                -m_singState: std::optional<int>
                -m_openState: std::optional<int>
                --constructors--
                +SingOpenStatePair(int state, bool isSing)
                +SingOpenStatePair(int singState, int openState)
                --member functions--
                +containsSingState(): bool
                +containsOpenState(): bool
                +singState(): int
                +openState(): int
            }

            GeneralPolyhedralAbstraction ..> ObservablePatchSequence
            GeneralPolyhedralAbstraction --> "*" ObservableTraversalNode
            GeneralPolyhedralAbstraction ..> SingOpenStatePair
    }


    package omnidirectional {
        class Tile {
            --data members--
            -m_observable: Observable
            -m_powerset: PowersetConstSharedPtr
            -m_closure: PowersetConstSharedPtr
            -m_hashcode: std::size_t
            --constructors--
            +Tile(const Tile& other)
            +Tile(Tile&& other)
            +Tile(Observable observable, PowersetSharedPtr patches)
            +Tile(Observable observable, const Powerset& patches)
            --member functions--
            +observable(): const Observable&
            +powerset(): PowersetConstSharedPtr
            +closure(): PowersetConstSharedPtr
            +spaceDimension(): PPL::dimension_type
            +hashcode(): std::size_t
            -computeClosurePatches(): void
            -computeHashCode(): void
            --operators--
            +operator!= (const Tile& tile1, const Tile& tile2): bool
            +operator== (const Tile& tile1, const Tile& tile2): bool
            +operator<< (std::ostream& os, const Tile& tile): std::ostream&
        }

        class TileExtractor {
             --data members--
             -m_currentObservable: const Observable*
             -m_patchesIndexesInFirstTile: std::unordered_set<int>
             --constructors--
             +TileExtractor()
             --member functions--
             +extractTiles(const std::vector<Observable>& observables): std::vector<Tile>
             +extractTiles(const Observable& observable): std::vector<Tile>
             -findFirstTile(): Tile
             -collectPatchesNotInFirstTile(): std::list<std::reference_wrapper<const Poly>>
             -findRemainingTiles(): std::vector<Tile>
             --static functions--
             {static} -border(const Poly& p, const Poly& q): PowersetUniquePtr
             {static} -areAdjacent(const Poly& p, const Poly& q): bool
        }

        class TileNode {
            --data members--
            -m_tile: Tile
            --constructors--
            +TileNode(const Tile& tile)
            +TileNode(const TileNode& other)
            +TileNode(TileNode&& other)
            --member functions--
            +observable(): const Observable&
            +points(): PowersetConstSharedPtr
            +isUniverse(): bool
            +spaceDimension(): PPL::dimension_type
            +isEmpty(): bool
            --operators--
            +operator!= (const TileNode& tileNode1, const TileNode& tileNode2) : bool
            +operator== (const TileNode& tileNode1, const TileNode& tileNode2) : bool
        }

        class TripleTileNode {
            --data members--
            -m_triple: std::tuple<Tile, Tile, Tile>
            -m_observable: Observable
            -m_points: PowersetConstSharedPtr
            --constructors--
            +TripleTileNode(const Tile& tile1, const Tile& tile2, const Tile& tile3)
            +TripleTileNode(const TileNode&)
            +TripleTileNode(TileNode&&)
            --member functions--
            +observable(): const Observable&
            +points(): PowersetConstSharedPtr
            +isUniverse(): bool
            +isEmpty(): bool
            +spaceDimension(): PPL::dimension_type
            -computeObservable(): void
            -computePoints(): void
            --operators--
            +operator!= (const TripleTileNode& tripleTileNode1, const TripleTileNode& tripleTileNode2) : bool
            +operator== (const TripleTileNode& tripleTileNode1, const TripleTileNode& tripleTileNode2) : bool
        }

        struct "std::hash<Tile>" as TileHash {
            +std::size_t operator() (const Tile& tile) const noexcept
        }

        class OmnidirectionalPolyhedralAbstraction {
            --type aliases--
            using EdgeIterator = spot::internal::state_out<spot::digraph<spot::twa_graph_state, spot::twa_graph_edge_data>>
            --data members--
            -m_graph: spot::twa_graph_ptr
            -m_tileNodes: std::unordered_map<unsigned, std::variant<TileNode, TripleTileNode>>
            --constructors--
            +OmnidirectionalPolyhedralAbstraction(PolyhedralSystemConstSharedPtr polyhedralSystem)
            --member functions--
            +observable(unsigned state): const Observable&
            +points(unsigned state): PowersetConstSharedPtr
            +initialState(): int
            +totalStates(): int
            +totalEdges(): int
            +successors(unsigned state): EdgeIterator
            +hasSuccessors(unsigned state): bool
            +countSuccessors(unsigned state): int
            +twa(): spot::const_twa_graph_ptr
            +printDotFormat(std::ostream& os): void
            -buildAbstraction(std::vector<Tile>&& tiles): void
            -initializeGraph(spot::bdd_dict_ptr bddDict): void
            -observableAsBdd(const Observable& observable): bdd
            -processTriple(const Tile& tile1, const Tile& tile2, const Tile& tile3, std::unordered_map<Tile, unsigned>& stateByTile): void
            -getStateByTileOrCreate(const Tile& tile, std::unordered_map<Tile, unsigned>& stateByTile): unsigned
        }

        Tile <..> TileHash
        Tile --> "1" Observable
        TileNode --> "1" Observable
        TileNode --> "1" Tile
        TripleTileNode --> "3" Observable
        TripleTileNode --> "3" Tile
        TileExtractor ..> Tile
        TileExtractor --> "0..1" Observable
        OmnidirectionalPolyhedralAbstraction --> "*" TileNode
        OmnidirectionalPolyhedralAbstraction --> "*" TripleTileNode
    }
}
@enduml
