@startuml
!include abstractions.puml
!include parser.puml
!include system.puml
!include automata.puml
!include discretisation.puml
!include mcsolvers.puml
!include cli.puml
!include stats.puml
!include product.puml


BackwardNFA ---> "1" DiscreteLtlFormula
PolyhedralSystemFormulaDenotationMap --> "1" PolyhedralSystem

PolyhedralSystemSymbolTableListener --> "1" PolyhedralSystemSymbolTable
PolyhedralSystemBuilderVisitor::PolyhedralSystemVisitor --> "1" PolyhedralSystemSymbolTable

RtlfParsingResult --> "0..1" spot::formula
PolyhedralSystemParsingResult --> "0..1" PolyhedralSystem
Denot --> "1" PolyhedralSystem
Denot --> "1" BackwardNFA

RtlMcProgram --> "1" PolyhedralSystem
RtlMcProgram --> "1" spot::formula
@enduml