@startuml
package mc <<Frame>> {
    class McPointBuilderVisitor {
        --data members--
        -m_visitor: McPointVisitor
        --constructors--
        +McPointBuilderVisitor(const PolyhedralSystemSymbolTable& symbolTable)
        --member functions--
        +buildMcPoint(McPointParser::ArrayContext* parseTree) : PPL::Generator
        +hasErrors() : bool
        +errors() : const std::vector<ParserError>&
    }

    class McPointBuilderVisitor::McPointVisitor {
        --data members--
        -m_valueByVariable : std::unordered_map<std::string, int>
        -m_symbolTable : std::reference_wrapper<PolyhedralSystemSymbolTable>
        -m_errors : std::vector<ParserError>
        --constructors--
        +McPointVisitor(PolyhedralSystemSymbolTable& symbolTable)
        --visit functions--
        +visitValidArray(McPointParser::ValidArrayContext* context) : std::any
        +visitValidPair(McPointParser::ValidPairContext* context) : std::any
        +visitValidValue(McPointParser::ValidValueContext* context) : std::any
        --private member functions--
        -symbolTableHasVariable(std::string_view variable): bool
        -addDuplicateVariableParserError(antlr4::tree::TerminalNode* ctx): void
        -addVariableNotPresentInPolySystemError(antlr4::tree::TerminalNode* ctx): void
        -addMissingVariablesError(McPointParser::ArrayContext* parseTree, std::vector<std::string>&& missingVariables): void
        --friends--
        class McPointBuilderVisitor
    }

    class McPointBaseVisitor <<antlr4>> {}

    object mcparser_h_cpp {
        +using RationalPointParsingResult = std::variant<PPL::Generator, std::vector<ParserError>>
        +parseRationalPoint(std::string_view input, const PolyhedralSystemSymbolTable& symbolTable) : RationalPointParsingResult
        +parseRationalPoint(std::istream& input, const PolyhedralSystemSymbolTable& symbolTable) : RationalPointParsingResult
        +parseRationalPoint(antlr4::ANTLRInputStream* input, const PolyhedralSystemSymbolTable& symbolTable) : RationalPointParsingResult
    }

    McPointBuilderVisitor::McPointVisitor ..|> McPointBaseVisitor
}

@enduml