name: Compile -> Test -> Build Docker Image

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'meson_options.txt'
      - 'meson.build'
      - 'src/**'
      - 'tests/**'
      - 'subprojects/**'
  pull_request:

jobs:
  runs:
    name: Compile -> Test -> Build Docker Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name : Add SHORT_SHA Environment Variable
        id   : short-sha
        shell: bash
        run  : echo "COMMIT_SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compile and Test
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vtramo/rtl-mc:build-${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: compile-test

      - name: Build release Docker image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vtramo/rtl-mc:${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: compile-release