name: Compile & Test & Push

on:
  push:
    paths:
      - '.github/workflows/compile-test-image.yaml'
      - 'Dockerfile'
      - 'meson_options.txt'
      - 'meson.build'
      - 'src/**'
      - 'tests/**'
      - 'subprojects/**'
  pull_request:

jobs:
  build-test-image-push:
    if: ${{ github.actor != 'dependabot[bot]' }}

    name: Compile -> Test -> Build Docker Image -> Push Docker Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add SHORT_SHA Environment Variable
        id: short-sha
        shell: bash
        run: echo "COMMIT_SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compile and Test
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: true
          tags: vtramo/rtl-mc:build-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: compile-test

      - name: Build release Docker image
        uses: docker/build-push-action@v6
        with:
          tags: vtramo/rtl-mc:${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

#      - name: Test release Docker Image
#        run: |
#          POLYHEDRAL_SYSTEM=$(cat << EOF
#          Inv ( { a >= 0 & b >= 0 } )
#          Flow { a + b >= -2 & a + b <= 2 & a >= -1 & a <= 1 & b >= -2 & b <= 2 & t = 1 }
#          p { a >= b + 1 }
#          q { b >= a + 1 }
#          t0 { t = 0 }
#          t1 { t <= 10 }
#          EOF
#          )
#
#          docker run --rm vtramo/rtl-mc:${{ env.COMMIT_SHORT_SHA }} echo "$(rtl-gen alternation -k 10) & t0 & G(t1)" | \
#          rtl-mc \
#            --system "$POLYHEDRAL_SYSTEM" \
#            --formula - \
#            --semantics fin \
#            --high

      - name: Push release Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: vtramo/rtl-mc:${{ env.COMMIT_SHORT_SHA }}
